
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lizhewen
 */
public class GUI extends javax.swing.JFrame {
    
    Passenger passengerObj = new Passenger();
    Flight flightObj = new Flight();
    Day dateObj = new Day();
    BookingQueries bkQrs = new BookingQueries();
    Waitlist wtlst = new Waitlist();
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        updatePassengerComboBox();
        updateFlightComboBox();
        updateDateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PassengerAndDayTab = new javax.swing.JPanel();
        PassengerNameLabel = new javax.swing.JLabel();
        PassengerNameTextField = new javax.swing.JTextField();
        AddPassengerButton = new javax.swing.JButton();
        Tab1Status = new javax.swing.JLabel();
        Tab1StatusMsg = new javax.swing.JLabel();
        AddDateTitleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        AddDateButton = new javax.swing.JButton();
        AddDateStatusLabel = new javax.swing.JLabel();
        AddDateStatusMsg = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        PassengerStatusLabel = new javax.swing.JLabel();
        PassengerStatusComboBox = new javax.swing.JComboBox<>();
        PassengerStatusButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        PassengerStatusTable = new javax.swing.JTable();
        addDateSpinner = new javax.swing.JSpinner();
        AddAndDropFlightTab = new javax.swing.JPanel();
        FlightNameLabel = new javax.swing.JLabel();
        FlightNameTextField = new javax.swing.JTextField();
        SeatNumLabel = new javax.swing.JLabel();
        SeatNumTextField = new javax.swing.JTextField();
        AddFlightButton = new javax.swing.JButton();
        AddFlightStatusLabel = new javax.swing.JLabel();
        AddFlightStatusMsg = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        DropFlightLabel = new javax.swing.JLabel();
        DropFlightComboBox = new javax.swing.JComboBox<>();
        DropFlightButton = new javax.swing.JButton();
        DropFlightStatusLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DropFlightStatusMsgTextArea = new javax.swing.JTextArea();
        AddAndCancelBookingTab = new javax.swing.JPanel();
        FlightComboBox = new javax.swing.JComboBox<>();
        FlightLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        DateComboBox = new javax.swing.JComboBox<>();
        PassengerLabel = new javax.swing.JLabel();
        AddBookingButton = new javax.swing.JButton();
        PassengerComboBox = new javax.swing.JComboBox<>();
        Tab2Status = new javax.swing.JLabel();
        Tab2StatusMsg = new javax.swing.JLabel();
        CancelPassengerLabel = new javax.swing.JLabel();
        CancelPassengerComboBox = new javax.swing.JComboBox<>();
        CancelDateLabel = new javax.swing.JLabel();
        CancelDateComboBox = new javax.swing.JComboBox<>();
        CancelBookingButton = new javax.swing.JButton();
        CancelBookingStatusLabel = new javax.swing.JLabel();
        CancelBookingStatusMsg = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        BookingStatusTab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ShowBookingFlightComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ShowBookingDayComboBox = new javax.swing.JComboBox<>();
        ShowBksShowButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ShowWaitlistTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        WtlstDayComboBox = new javax.swing.JComboBox<>();
        WtlstShowButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        WtlstTable = new javax.swing.JTable();
        TitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PassengerNameLabel.setText("Passenger Name:");

        PassengerNameTextField.setColumns(20);

        AddPassengerButton.setText("Add");
        AddPassengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPassengerButtonActionPerformed(evt);
            }
        });

        Tab1Status.setText("Status: ");

        Tab1StatusMsg.setText("N/A");

        AddDateTitleLabel.setText("Date: ");

        AddDateButton.setText("Add");
        AddDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDateButtonActionPerformed(evt);
            }
        });

        AddDateStatusLabel.setText("Status:");

        AddDateStatusMsg.setText("N/A");

        PassengerStatusLabel.setText("Passenger: ");

        PassengerStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PassengerStatusButton.setText("Show Status");
        PassengerStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassengerStatusButtonActionPerformed(evt);
            }
        });

        PassengerStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Passenger", "Flight", "Day", "Timestamp", "Status"
            }
        ));
        jScrollPane4.setViewportView(PassengerStatusTable);

        addDateSpinner.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout PassengerAndDayTabLayout = new javax.swing.GroupLayout(PassengerAndDayTab);
        PassengerAndDayTab.setLayout(PassengerAndDayTabLayout);
        PassengerAndDayTabLayout.setHorizontalGroup(
            PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengerAndDayTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PassengerAndDayTabLayout.createSequentialGroup()
                            .addGroup(PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Tab1Status)
                                .addComponent(PassengerNameLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PassengerAndDayTabLayout.createSequentialGroup()
                                    .addComponent(PassengerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AddPassengerButton))
                                .addComponent(Tab1StatusMsg)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(PassengerAndDayTabLayout.createSequentialGroup()
                        .addGroup(PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PassengerAndDayTabLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(AddDateStatusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddDateStatusMsg))
                            .addGroup(PassengerAndDayTabLayout.createSequentialGroup()
                                .addComponent(AddDateTitleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddDateButton))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PassengerAndDayTabLayout.createSequentialGroup()
                        .addComponent(PassengerStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PassengerStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PassengerStatusButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        PassengerAndDayTabLayout.setVerticalGroup(
            PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengerAndDayTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassengerNameLabel)
                    .addComponent(PassengerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPassengerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tab1Status)
                    .addComponent(Tab1StatusMsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDateButton)
                    .addComponent(AddDateTitleLabel)
                    .addComponent(addDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDateStatusLabel)
                    .addComponent(AddDateStatusMsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PassengerAndDayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassengerStatusLabel)
                    .addComponent(PassengerStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerStatusButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Passenger & Date", PassengerAndDayTab);

        FlightNameLabel.setText("Flight Name: ");

        FlightNameTextField.setColumns(8);

        SeatNumLabel.setText("Seat Number: ");

        SeatNumTextField.setColumns(5);

        AddFlightButton.setText("Add");
        AddFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightButtonActionPerformed(evt);
            }
        });

        AddFlightStatusLabel.setText("Status: ");

        AddFlightStatusMsg.setText("N/A");

        DropFlightLabel.setText("Flight: ");

        DropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropFlightButton.setText("Drop");
        DropFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropFlightButtonActionPerformed(evt);
            }
        });

        DropFlightStatusLabel.setText("Status: ");

        DropFlightStatusMsgTextArea.setEditable(false);
        DropFlightStatusMsgTextArea.setColumns(20);
        DropFlightStatusMsgTextArea.setRows(5);
        jScrollPane3.setViewportView(DropFlightStatusMsgTextArea);

        javax.swing.GroupLayout AddAndDropFlightTabLayout = new javax.swing.GroupLayout(AddAndDropFlightTab);
        AddAndDropFlightTab.setLayout(AddAndDropFlightTabLayout);
        AddAndDropFlightTabLayout.setHorizontalGroup(
            AddAndDropFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddAndDropFlightTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddAndDropFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddAndDropFlightTabLayout.createSequentialGroup()
                        .addGroup(AddAndDropFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddFlightStatusLabel)
                            .addComponent(FlightNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddAndDropFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddAndDropFlightTabLayout.createSequentialGroup()
                                .addComponent(FlightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SeatNumLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SeatNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(AddFlightButton))
                            .addGroup(AddAndDropFlightTabLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(AddFlightStatusMsg))))
                    .addGroup(AddAndDropFlightTabLayout.createSequentialGroup()
                        .addComponent(DropFlightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DropFlightButton))
                    .addGroup(AddAndDropFlightTabLayout.createSequentialGroup()
                        .addComponent(DropFlightStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        AddAndDropFlightTabLayout.setVerticalGroup(
            AddAndDropFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddAndDropFlightTabLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(AddAndDropFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightNameLabel)
                    .addComponent(FlightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeatNumLabel)
                    .addComponent(SeatNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFlightButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddAndDropFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFlightStatusLabel)
                    .addComponent(AddFlightStatusMsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddAndDropFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DropFlightLabel)
                    .addComponent(DropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropFlightButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddAndDropFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DropFlightStatusLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add & Drop Flight", AddAndDropFlightTab);

        FlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));

        FlightLabel.setText("Flight:");

        DateLabel.setText("Date:");

        DateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));

        PassengerLabel.setText("Passenger: ");

        AddBookingButton.setText("Add Booking");
        AddBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookingButtonActionPerformed(evt);
            }
        });

        PassengerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));

        Tab2Status.setText("Status:");

        Tab2StatusMsg.setText("N/A");

        CancelPassengerLabel.setText("Passenger: ");

        CancelPassengerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CancelDateLabel.setText("Date: ");

        CancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CancelBookingButton.setText("Cancel Booking");
        CancelBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBookingButtonActionPerformed(evt);
            }
        });

        CancelBookingStatusLabel.setText("Status: ");

        CancelBookingStatusMsg.setText("N/A");

        javax.swing.GroupLayout AddAndCancelBookingTabLayout = new javax.swing.GroupLayout(AddAndCancelBookingTab);
        AddAndCancelBookingTab.setLayout(AddAndCancelBookingTabLayout);
        AddAndCancelBookingTabLayout.setHorizontalGroup(
            AddAndCancelBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddAndCancelBookingTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddAndCancelBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddAndCancelBookingTabLayout.createSequentialGroup()
                        .addComponent(Tab2Status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tab2StatusMsg)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AddAndCancelBookingTabLayout.createSequentialGroup()
                        .addComponent(jSeparator4)
                        .addContainerGap())
                    .addGroup(AddAndCancelBookingTabLayout.createSequentialGroup()
                        .addComponent(FlightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(DateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(PassengerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PassengerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))
                    .addGroup(AddAndCancelBookingTabLayout.createSequentialGroup()
                        .addGroup(AddAndCancelBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddAndCancelBookingTabLayout.createSequentialGroup()
                                .addComponent(CancelBookingStatusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelBookingStatusMsg))
                            .addGroup(AddAndCancelBookingTabLayout.createSequentialGroup()
                                .addComponent(CancelPassengerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelPassengerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(CancelDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddAndCancelBookingTabLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(AddAndCancelBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddBookingButton)
                                    .addComponent(CancelBookingButton))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        AddAndCancelBookingTabLayout.setVerticalGroup(
            AddAndCancelBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddAndCancelBookingTabLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(AddAndCancelBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightLabel)
                    .addComponent(FlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateLabel)
                    .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerLabel)
                    .addComponent(PassengerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddBookingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddAndCancelBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tab2Status)
                    .addComponent(Tab2StatusMsg))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AddAndCancelBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelPassengerLabel)
                    .addComponent(CancelPassengerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelDateLabel)
                    .addComponent(CancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelBookingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddAndCancelBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBookingStatusLabel)
                    .addComponent(CancelBookingStatusMsg))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add & Cancel Booking", AddAndCancelBookingTab);

        jLabel3.setText("Flight:");

        ShowBookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));

        jLabel4.setText("Day:");

        ShowBookingDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));

        ShowBksShowButton.setText("Show");
        ShowBksShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBksShowButtonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Passenger", "Flight", "Day", "Timestamp"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout BookingStatusTabLayout = new javax.swing.GroupLayout(BookingStatusTab);
        BookingStatusTab.setLayout(BookingStatusTabLayout);
        BookingStatusTabLayout.setHorizontalGroup(
            BookingStatusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingStatusTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowBookingFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowBookingDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowBksShowButton)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        BookingStatusTabLayout.setVerticalGroup(
            BookingStatusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingStatusTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookingStatusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ShowBookingFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ShowBookingDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowBksShowButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Show Bookings", BookingStatusTab);

        jLabel5.setText("Day:");

        WtlstDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));

        WtlstShowButton.setText("Show");
        WtlstShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WtlstShowButtonActionPerformed(evt);
            }
        });

        WtlstTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Passenger", "Flight", "Day", "Timestamp"
            }
        ));
        jScrollPane2.setViewportView(WtlstTable);

        javax.swing.GroupLayout ShowWaitlistTabLayout = new javax.swing.GroupLayout(ShowWaitlistTab);
        ShowWaitlistTab.setLayout(ShowWaitlistTabLayout);
        ShowWaitlistTabLayout.setHorizontalGroup(
            ShowWaitlistTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowWaitlistTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WtlstDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WtlstShowButton)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        ShowWaitlistTabLayout.setVerticalGroup(
            ShowWaitlistTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowWaitlistTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ShowWaitlistTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(WtlstDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WtlstShowButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Show Waitlist", ShowWaitlistTab);

        TitleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Flight Scheduler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WtlstShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WtlstShowButtonActionPerformed
        Date date = Date.valueOf(WtlstDayComboBox.getSelectedItem().toString());
        Object[][] tableData = wtlst.getWaitlistByDay(date);
        WtlstTable.setModel(new javax.swing.table.DefaultTableModel(
            tableData,
            new String [] {"Passenger", "Flight", "Day", "Timestamp"}));
    }//GEN-LAST:event_WtlstShowButtonActionPerformed

    private void ShowBksShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowBksShowButtonActionPerformed
        String flight = ShowBookingFlightComboBox.getSelectedItem().toString();
        Date date = Date.valueOf(ShowBookingDayComboBox.getSelectedItem().toString());
        Object[][] tableData = bkQrs.statusByFlightDay(date, flight);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            tableData,
            new String [] {"Passenger", "Flight", "Day", "Timestamp"}));
    }//GEN-LAST:event_ShowBksShowButtonActionPerformed

    private void AddBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookingButtonActionPerformed
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        String flight = FlightComboBox.getSelectedItem().toString();
        Date date = Date.valueOf(DateComboBox.getSelectedItem().toString());
        String passenger = PassengerComboBox.getSelectedItem().toString();
        int availableSeats = flightObj.getAvailableSeats(flight, date);
        if (availableSeats > 0) {
            bkQrs.addBooking(passenger, date, flight, currentTimestamp);
            Tab2StatusMsg.setText("You are Succesfully BOOKED for " + flight + " on " + date);
        }
        else if (availableSeats == 0) {
            wtlst.addWaitlist(passenger, date, flight, currentTimestamp);
            Tab2StatusMsg.setText("You are put on WAITLIST for " + flight + " on " + date);
        }
        else {
            Tab2StatusMsg.setText("Action Failed!");
        }
    }//GEN-LAST:event_AddBookingButtonActionPerformed

    private void AddPassengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPassengerButtonActionPerformed
        String name = PassengerNameTextField.getText();
        int result = passengerObj.addPerson(name);
        Tab1StatusMsg.setText("processing...");
        if (result == 1) {
            Tab1StatusMsg.setText("Done!");
            updatePassengerComboBox();
        }
        else
            Tab1StatusMsg.setText("Failed!");
    }//GEN-LAST:event_AddPassengerButtonActionPerformed

    private void AddFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightButtonActionPerformed
        String flightName = FlightNameTextField.getText();
        int seatNum = Integer.valueOf(SeatNumTextField.getText());
        int result = flightObj.addFlight(flightName, seatNum);
        AddFlightStatusMsg.setText("processing...");
        if (result == 1) {
            AddFlightStatusMsg.setText("Done!");
            updateFlightComboBox();
        }
        else
            AddFlightStatusMsg.setText("Failed!");
    }//GEN-LAST:event_AddFlightButtonActionPerformed

    private void PassengerStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassengerStatusButtonActionPerformed
        String passenger = PassengerStatusComboBox.getSelectedItem().toString();
        Object[][] tableData = passengerObj.statusCustomer(passenger);
        PassengerStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            tableData,
            new String [] {"Passenger", "Flight", "Day", "Timestamp", "Status"}));
    }//GEN-LAST:event_PassengerStatusButtonActionPerformed

    private void CancelBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBookingButtonActionPerformed
        CancelBookingStatusMsg.setText("processing...");
        String passenger = CancelPassengerComboBox.getSelectedItem().toString();
        Date day = Date.valueOf(CancelDateComboBox.getSelectedItem().toString());
        String flight = bkQrs.cancelBooking(passenger, day);
        if (flight != null) {
            int result = bkQrs.bookPassenger(flight, day);
            CancelBookingStatusMsg.setText("Done! " + result + " passenger has been booked from waitlist.");
        }
        else
            CancelBookingStatusMsg.setText("Failed!");
    }//GEN-LAST:event_CancelBookingButtonActionPerformed

    private void AddDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDateButtonActionPerformed
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(addDateSpinner.getValue());
        Date day = Date.valueOf(spinnerValue);
        int result = dateObj.addDate(day);
        AddDateStatusMsg.setText("processing...");
        if (result == 1) {
            AddDateStatusMsg.setText("Done!");
            updateDateComboBox();
        }
        else
            AddDateStatusMsg.setText("Failed!");
    }//GEN-LAST:event_AddDateButtonActionPerformed

    private void DropFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropFlightButtonActionPerformed
        String flight = DropFlightComboBox.getSelectedItem().toString();
        if (flightObj.dropFlight(flight) == 1) {
            DropFlightStatusMsgTextArea.append("1 flight has been successully dropped from the system.\n");
            updateFlightComboBox();
            String msg = bkQrs.rebookPassengers(flight);
            DropFlightStatusMsgTextArea.append(msg);
        }
        else
            DropFlightStatusMsgTextArea.append("Failed");
    }//GEN-LAST:event_DropFlightButtonActionPerformed
    
    private void updatePassengerComboBox() {
        String[] list = Passenger.getAllPassenger();
        PassengerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        PassengerStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        CancelPassengerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(list));
    }
    
    private void updateFlightComboBox() {
        String[] list = Flight.getFlights();
        FlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        DropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        ShowBookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(list));
    }
    
    private void updateDateComboBox() {
        String[] list = Day.getDates();
        DateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        CancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        ShowBookingDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        WtlstDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(list));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddAndCancelBookingTab;
    private javax.swing.JPanel AddAndDropFlightTab;
    private javax.swing.JButton AddBookingButton;
    private javax.swing.JButton AddDateButton;
    private javax.swing.JLabel AddDateStatusLabel;
    private javax.swing.JLabel AddDateStatusMsg;
    private javax.swing.JLabel AddDateTitleLabel;
    private javax.swing.JButton AddFlightButton;
    private javax.swing.JLabel AddFlightStatusLabel;
    private javax.swing.JLabel AddFlightStatusMsg;
    private javax.swing.JButton AddPassengerButton;
    private javax.swing.JPanel BookingStatusTab;
    private javax.swing.JButton CancelBookingButton;
    private javax.swing.JLabel CancelBookingStatusLabel;
    private javax.swing.JLabel CancelBookingStatusMsg;
    private javax.swing.JComboBox<String> CancelDateComboBox;
    private javax.swing.JLabel CancelDateLabel;
    private javax.swing.JComboBox<String> CancelPassengerComboBox;
    private javax.swing.JLabel CancelPassengerLabel;
    private javax.swing.JComboBox<String> DateComboBox;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JButton DropFlightButton;
    private javax.swing.JComboBox<String> DropFlightComboBox;
    private javax.swing.JLabel DropFlightLabel;
    private javax.swing.JLabel DropFlightStatusLabel;
    private javax.swing.JTextArea DropFlightStatusMsgTextArea;
    private javax.swing.JComboBox<String> FlightComboBox;
    private javax.swing.JLabel FlightLabel;
    private javax.swing.JLabel FlightNameLabel;
    private javax.swing.JTextField FlightNameTextField;
    private javax.swing.JPanel PassengerAndDayTab;
    private javax.swing.JComboBox<String> PassengerComboBox;
    private javax.swing.JLabel PassengerLabel;
    private javax.swing.JLabel PassengerNameLabel;
    private javax.swing.JTextField PassengerNameTextField;
    private javax.swing.JButton PassengerStatusButton;
    private javax.swing.JComboBox<String> PassengerStatusComboBox;
    private javax.swing.JLabel PassengerStatusLabel;
    private javax.swing.JTable PassengerStatusTable;
    private javax.swing.JLabel SeatNumLabel;
    private javax.swing.JTextField SeatNumTextField;
    private javax.swing.JButton ShowBksShowButton;
    private javax.swing.JComboBox<String> ShowBookingDayComboBox;
    private javax.swing.JComboBox<String> ShowBookingFlightComboBox;
    private javax.swing.JPanel ShowWaitlistTab;
    private javax.swing.JLabel Tab1Status;
    private javax.swing.JLabel Tab1StatusMsg;
    private javax.swing.JLabel Tab2Status;
    private javax.swing.JLabel Tab2StatusMsg;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JComboBox<String> WtlstDayComboBox;
    private javax.swing.JButton WtlstShowButton;
    private javax.swing.JTable WtlstTable;
    private javax.swing.JSpinner addDateSpinner;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
